#
###################################
# Site wide configuration
####################################
#
title: thaidv96 | Data Science and Applications
email: thaidv96@gmail.com
description: Khoa học dữ liệu và ứng dụng.
url: # the base hostname & protocol for your site
keywords: ["blog", "data science", "computer vision", "nlp"]

#
###################################
# Jekyll configuration
####################################
#
timezone: Asia/Bangkok
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  math_engine: mathjax

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: thaidv96
  avatar: avatar.jpg
  job: "Data Enthusiast"
  bio: "Great things start with small beginnings."
  email: thaidv96@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: thaidoan.ftu
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: thaidv96
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: thaidoan96
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
